steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/tirev, '.']
- name: gcr.io/cloud-builders/docker
  args: [tag, gcr.io/$PROJECT_ID/tirev, gcr.io/$PROJECT_ID/tirev:$TAG_NAME]

images:
- gcr.io/$PROJECT_ID/tirev
- gcr.io/$PROJECT_ID/tirev:$TAG_NAME
