name: Release
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v1
      id: auth
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        token_format: access_token
    - uses: docker/login-action@v2
      with:
        registry: us-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - uses: docker/setup-buildx-action@v2
      with:
        version: latest
        platforms: linux/amd64
    - uses: docker/build-push-action@v4
      with:
        provenance: false
        build-args: |
          VERSION=${{ github.ref_name }}
        push: true
        tags:
        - us-docker.pkg.dev/moonrhythm-containers/gcr.io/tirev:${{ github.ref_name }}
        - us-docker.pkg.dev/moonrhythm-containers/gcr.io/tirev:latest
